### ISSUE TITLE
Cannot Bypass Privacy Error in Chrome for Swagger UI

### ISSUE THREAD

**Issue by dkelosky** [zowe/sample-spring-boot-api-service#64]
I'm not sure if there was a change in the repo or in Chrome, but when I attempt to see the swagger UI for a service deployed to z/OS in by browser I now get this error (which I can no longer bypass in Chrome):

![image](https://user-images.githubusercontent.com/14940561/67480990-118f2380-f62f-11e9-8d51-f7d2e04d3329.png)

Has there been some change to cause this?

**Comment by dkelosky** [comment]
I'll casually experiment why `https://github.com/zowe/sample-spring-boot-api-service/blob/master/zowe-rest-api-sample-spring/src/main/java/org/zowe/sample/apiservice/config/WebSecurityConfig.java#L34` doesn't seem to take effect here.

**Comment by plavjanik** [comment]
The sample application should not set HSTS headers. If it does then it is a bug. I do not think that the sample does that. It can be set by another app running on the same host because this setting applies to the host and the port is ignored. 

There are two options as a workaround:
1. Remove the setting using the procedure in https://www.ssl2buy.com/wiki/how-to-clear-hsts-settings-on-chrome-firefox-and-ie-browsers
2. Open a new incognito window in your browser

It would be good to find out what service sets it because it should not because this forbids HTTP.

**Comment by dkelosky** [comment]
Hi Petr,

Option 2 worked for me, but I don't really understand why.  I'll close this in the meantime and later adjust my Chrome config.

Thank you,
Dan
